---
pagetitle: Yung-Yu Tsai
---

<link rel="stylesheet" href="styles.css" type="text/css">
<style>
  body{
  font-size: 12pt;
}
</style>


### Teaching Experience (Instructor of Record)
<div style="line-height:50%;"><br></div>

#### _University of Missouri (Columbia, MO)_

* State Government, 2024 Spring _(Undergraduate, Online)_
  - Graduate Instructor

------

### Teaching Experience (TA)
<div style="line-height:50%;"><br></div>

#### _University of Missouri (Columbia, MO)_

* State Government, 2023 Fall _(Undergraduate, In-person)_
  - Graduate Teaching Assistant
  
<div style="line-height:50%;"><br></div>

* Research Methods and Inquiry in Public Affairs I, 2023 Spring. _(Graduate, Online)_
  - Graduate Teaching Assistant

<div style="line-height:50%;"><br></div>

* Research Methods and Inquiry in Public Affairs II, 2023 Spring. _(Graduate, Online)_
  - Graduate Teaching Assistant
  
<div style="line-height:50%;"><br></div>

* American Government, 2021 Fall _(Undergraduate, Online)_
  - Graduate Teaching Assistant

<div style="line-height:100%;"><br></div>

#### _National Chengchi University (Taipei, Taiwan)_

* Fundamental Statistics for Public Administration, 2019 Spring _(Undergraduate, In-person)_
  - Teaching Assistant
  - Outstanding Teaching Assistant Award

<div style="line-height:50%;"><br></div>
  
* Introduction to Statistics, 2018 Fall _(Graduate, In-person)_
  - Teaching Assistant

------

### Guest Lecture

* Introduction To Public And Nonprofit Management (University of Missouri) _(November, 2023)_
  - Topic: Civil service system

<div style="line-height:50%;"><br></div>

* Chinese Politics and Foreign Policy (University of Missouri) _(March, 2023)_
  - Topic: Politics of education: How education affects political participation and national identity in Chinese countries

<div style="line-height:50%;"><br></div>

* Quantitative Research Method (National Chengchi University) _(May, 2019)_
  - Topic: Application of administrative record data
  
  
------

### Workshop Speaker

* TSGPA Method Workshop (University of Missouri) _(October, 2023)_
  - Topic: Navigating Errors in Stata

 <div style="line-height:50%;"><br></div>

* TSGPA Women in Econometrics Group (University of Missouri) _(April, 2022)_
  - Topic: Stagger Difference-in-Differences
 
 <div style="line-height:50%;"><br></div>

* R-Ladies Taipei _(January, 2019)_
  - Topic: Application of government open data with geographic information systems (GIS)
